# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: fruit_num 东东农场
on:
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: fruit
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      # 继续浇水，设定剩余水滴数
      ISWATER: true
      RETAIN_NUM: 15800
      # 浇至直接兑换，条件：当剩余水滴数 大于 所差的水滴数
      ISMaxWATER: false
      # 删除好友
      ISDEL: false
      DEL_CODE:
    steps:
      - name: Checkout
        run: |
          ${{ secrets.JD_HTTPS }}
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          cd ~/scripts
          npm install
             
      - name: '运行继续浇水 【东东农场】'
        if: env.ISWATER == 'true'
        run: |
          cd ~/scripts
          node jd_fruit_num.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE_WZ }}
          FRUIT_ISWATER: ${{ env.ISWATER }}
          FRUIT_RETAIN_NUM: ${{ env.RETAIN_NUM }}
          FRUIT_ISMaxWATER: ${{ env.RETAIN_ISMaxWATER }}

      - name: '运行删除好友 【东东农场】'
        if: env.ISDEL == 'true'
        run: |
          cd ~/scripts
          node jd_fruit_num.js
        env:
          JD_COOKIE: ${{ secrets.JD_COOKIE_DD }}
          FRUIT_ISDEL: ${{ env.ISDEL }}
          FRUIT_DEL_CODE: ${{ env.DEL_CODE }}